# Auth
AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"

# Validation
VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD"
VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT"
VALIDATION_FILE_TOO_LARGE = "VALIDATION_FILE_TOO_LARGE"
VALIDATION_UNSUPPORTED_FORMAT = "VALIDATION_UNSUPPORTED_FORMAT"
VALIDATION_EMPTY_FILE = "VALIDATION_EMPTY_FILE"
VALIDATION_MISSING_COLUMN = "VALIDATION_MISSING_COLUMN"

# Business logic
OPENING_BALANCE_UNRESOLVED = "OPENING_BALANCE_UNRESOLVED"
FX_RATE_MISSING = "FX_RATE_MISSING"
INVESTMENT_POLICY_NOT_UPLOADED = "INVESTMENT_POLICY_NOT_UPLOADED"
ACCOUNT_RESTRICTED = "ACCOUNT_RESTRICTED"

# Jobs
JOB_NOT_FOUND = "JOB_NOT_FOUND"
JOB_STILL_PROCESSING = "JOB_STILL_PROCESSING"
JOB_FAILED = "JOB_FAILED"

# Data
DATA_STALE = "DATA_STALE"
DATA_MISSING_FEED = "DATA_MISSING_FEED"

# Agent errors
AGENT_ERROR = "AGENT_ERROR"
